debug: false
spring:
  datasource:
    url: jdbc:h2:mem:oddballdb
    username: oddball
    password: oddball
    driverClassName: org.h2.Driver
  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
  output.ansi.enabled: always
